"""initial configuration

Revision ID: 41e38b3112e0
Revises: 
Create Date: 2025-12-19 15:18:44.769641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41e38b3112e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_data', sa.LargeBinary(), nullable=False),
    sa.Column('phase_tag', sa.String(), nullable=False),
    sa.Column('goal_obj', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('prereq_obj', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('phases_obj', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('dailies_obj', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("phase_tag IN ('define_goal', 'get_prerequisites', 'generate_phases', 'refine_phases', 'generate_dailies')", name='check_phase_tag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_session_id'), 'users', ['session_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('related_experience', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('possible_gap_assessment', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('time_commitment_per_week_hours', sa.Float(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('required_resources', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('blocked_time_blocks', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_deadline'), 'goals', ['deadline'], unique=False)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_metric'), 'goals', ['metric'], unique=False)
    op.create_index(op.f('ix_goals_owner_id'), 'goals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_goals_purpose'), 'goals', ['purpose'], unique=False)
    op.create_index(op.f('ix_goals_title'), 'goals', ['title'], unique=False)
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('estimated_end_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phases_goal_id'), 'phases', ['goal_id'], unique=False)
    op.create_index(op.f('ix_phases_id'), 'phases', ['id'], unique=False)
    op.create_table('dailies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('dailies_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailies_id'), 'dailies', ['id'], unique=False)
    op.create_index(op.f('ix_dailies_phase_id'), 'dailies', ['phase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dailies_phase_id'), table_name='dailies')
    op.drop_index(op.f('ix_dailies_id'), table_name='dailies')
    op.drop_table('dailies')
    op.drop_index(op.f('ix_phases_id'), table_name='phases')
    op.drop_index(op.f('ix_phases_goal_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_index(op.f('ix_goals_title'), table_name='goals')
    op.drop_index(op.f('ix_goals_purpose'), table_name='goals')
    op.drop_index(op.f('ix_goals_owner_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_metric'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_deadline'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_users_session_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
