"""

Revision ID: 71299d00be1c
Revises: 1e196264bf67
Create Date: 2025-11-13 12:56:45.741108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71299d00be1c'
down_revision: Union[str, Sequence[str], None] = '1e196264bf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_end_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phases_goal_id'), 'phases', ['goal_id'], unique=False)
    op.create_index(op.f('ix_phases_id'), 'phases', ['id'], unique=False)
    op.create_table('dailies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailies_id'), 'dailies', ['id'], unique=False)
    op.create_index(op.f('ix_dailies_phase_id'), 'dailies', ['phase_id'], unique=False)
    op.add_column('goals', sa.Column('metric', sa.Text(), nullable=False))
    op.add_column('goals', sa.Column('purpose', sa.Text(), nullable=False))
    op.add_column('goals', sa.Column('deadline', sa.Date(), nullable=False))
    op.add_column('goals', sa.Column('prerequisites', sa.Text(), nullable=True))
    op.create_index(op.f('ix_goals_deadline'), 'goals', ['deadline'], unique=False)
    op.create_index(op.f('ix_goals_metric'), 'goals', ['metric'], unique=False)
    op.create_index(op.f('ix_goals_purpose'), 'goals', ['purpose'], unique=False)
    op.drop_column('goals', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_goals_purpose'), table_name='goals')
    op.drop_index(op.f('ix_goals_metric'), table_name='goals')
    op.drop_index(op.f('ix_goals_deadline'), table_name='goals')
    op.drop_column('goals', 'prerequisites')
    op.drop_column('goals', 'deadline')
    op.drop_column('goals', 'purpose')
    op.drop_column('goals', 'metric')
    op.drop_index(op.f('ix_dailies_phase_id'), table_name='dailies')
    op.drop_index(op.f('ix_dailies_id'), table_name='dailies')
    op.drop_table('dailies')
    op.drop_index(op.f('ix_phases_id'), table_name='phases')
    op.drop_index(op.f('ix_phases_goal_id'), table_name='phases')
    op.drop_table('phases')
    # ### end Alembic commands ###
