from .dailies import DAILIES_GENERATION_INSTRUCTIONS
from .definition import DEFINITION_INSTRUCTION
from .phase_generation import PHASE_GENERATION_INSTRUCTION
from .phase_refinement import PHASE_REFINEMENT_INSTRUCTION
from .prerequisite import GOAL_PREREQUISITE_INSTRUCTION